controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    position_controllers:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controllers:
  ros__parameters:
    joints:
      - right_elbw_rev
      - right_shldr_rev
      # - z_prism
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
